<script>
    import { onMount } from 'svelte';
    import { gsap } from 'gsap';
    import { Link, useForm } from '@inertiajs/svelte';
    import AuthLayout from '../../Layouts/AuthLayout.svelte';

    let formElements;
    let title;

    const form = useForm({
        code: ''
    });

    onMount(() => {
        gsap.from(title, { opacity: 0, x: -20, duration: 0.6, delay: 0.3, ease: 'power3.out' });
        gsap.from(formElements.children, {
            opacity: 0,
            y: 15,
            duration: 0.5,
            stagger: 0.1,
            delay: 0.4,
            ease: 'power2.out'
        });
    });

    function submit() {
        $form.post('/two-factor-challenge');
    }
</script>

<svelte:head>
    <title>Two-Factor Authentication - SSO Yado</title>
</svelte:head>

<AuthLayout>
    <h2 bind:this={title} class="text-2xl font-semibold mb-2 text-base-content">Security Check</h2>
    <p class="text-xs text-base-content/60 mb-6">Enter the 6-digit TOTP code generated by your Authenticator app.</p>

    <form on:submit|preventDefault={submit} bind:this={formElements} class="space-y-4">
        {#if $form.errors.code}
            <div class="p-3 rounded-xl bg-error/10 text-error text-xs border border-error/20">
                {$form.errors.code}
            </div>
        {/if}

        <div class="form-control">
            <label class="label" for="totp-code"><span class="label-text font-medium">Authentication Code</span></label>
            <input
                id="totp-code"
                type="text"
                bind:value={$form.code}
                inputmode="numeric"
                autocomplete="one-time-code"
                placeholder="123456"
                required
                maxlength="8"
                class="input input-bordered w-full text-center tracking-widest font-mono text-xl rounded-xl bg-base-100 focus:border-base-content"
            />
        </div>

        <button type="submit" class="btn btn-neutral w-full mt-4 rounded-xl shadow-lg shadow-neutral/20" disabled={$form.processing}>
            {#if $form.processing}
                <span class="loading loading-spinner loading-sm"></span>
            {:else}
                Verify & Continue
            {/if}
        </button>

        <div class="text-center mt-6 text-sm text-base-content/60">
            Having trouble?
            <Link href="/login" class="font-semibold text-base-content hover:underline transition-colors">Back to Login</Link>
        </div>
    </form>
</AuthLayout>
